// Aliases.
let Application = PIXI.Application;
let Graphics = PIXI.Graphics;

// let appWidth = 1500;
// let appHeight = 750;
let appWidth = window.innerWidth;
let appHeight = window.innerHeight;

// Initiate the application.
let app = new Application({
    width: appWidth,
    height: appHeight,
    antialias: true,
    transparent: false,
    resolution: 1
});

app.renderer.view.style.position = "absolute";
app.renderer.view.style.display = "block";
app.renderer.autoResize = true;
app.renderer.resize(window.innerWidth, window.innerHeight);

let waves = new Set();

function setup() {

    for (let i = 0; i < 10; i++) {

        // Create a new wave at random coordinates and random max radius.
        let wave = new Wave();

        waves.add(wave);

        // Draw wave on the screen.
        for (let gc of wave.getGraphicalComponents()) {
            app.stage.addChild(gc);
        }
    }

    app.ticker.add(delta => gameloop(delta));
}

function gameloop(delta) {

    // Make the waves grow no more than their maximum size.
    for (let wave of waves) {
        if (wave.radius < wave.max_radius ) {
            wave.expand();
        } else {
            
            // Remove the wave from the screen.
            for (let gc of wave.getGraphicalComponents()) {
                app.stage.removeChild(gc);
            }

            // Remove the wave from the set of waves.
            waves.delete(wave);

            // Add a new wave starting at a random position.
            let newWave = new Wave();

            waves.add(newWave);

            for (let gc of newWave.getGraphicalComponents()) {
                app.stage.addChild(gc);
            }
        }
    }
}

setup();

// Add the canvas generated by PIXI to the DOM.
document.body.appendChild(app.view);


function Wave(x_coordinate, y_coordinate, max_radius) {
    
    this.x_coordinate = x_coordinate || generateRandomCoordinates()[0];
    this.y_coordinate = y_coordinate || generateRandomCoordinates()[1];
    this.max_radius = max_radius || generateRandomMaximumRadius();

    this.radius = 3; // Initial radius.

    this.createCircle = function(color, radius) {
        let circle = new Graphics();
        circle.beginFill(color);
        circle.drawCircle(0, 0, radius);
        circle.beginHole();
        circle.drawCircle(0, 0, radius - 0.1);
        circle.endHole();
        circle.endFill();
        circle.x = this.x_coordinate;
        circle.y = this.y_coordinate;
        return circle;
    };

    this.outerCircle = this.createCircle(0xFFFFFF, this.radius);

    this.expand = function() {
        let sizeIncrement = 2;
        
        this.radius += sizeIncrement;

        this.outerCircle.width += sizeIncrement;
        this.outerCircle.height += sizeIncrement;
    }

    this.getGraphicalComponents = function() {
        return [this.outerCircle];
    }

}

function generateRandomMaximumRadius() {
    let max_radius = Math.floor(Math.random() * 100 + 50);
    return max_radius;
}

function generateRandomCoordinates() {
    let x_coordinate = Math.floor(Math.random() * appWidth);
    let y_coordinate = Math.floor(Math.random() * appHeight);

    return [x_coordinate, y_coordinate];
}