// Aliases.
let Application = PIXI.Application;
let Graphics = PIXI.Graphics;

let appWidth = 500;
let appHeight = 500;

// Initiate the application.
let app = new Application({
    width: appWidth,
    height: appHeight,
    antialias: true,
    transparent: false,
    resolution: 1
});

let outerCircle;
let innerCircle;

function setup() {
    outerCircle = createCircle(appWidth / 2, appHeight / 2, 10, 0xFFFFFF);
    innerCircle = createCircle(appWidth / 2, appHeight / 2, 9, 0x000000);

    app.stage.addChild(outerCircle);
    app.stage.addChild(innerCircle);
    app.ticker.add(delta => gameloop(delta));
}

function gameloop(delta) {
    if (outerCircle.width < 400 && innerCircle.width < 400) {
        increaseCircleSize(outerCircle);
        increaseCircleSize(innerCircle);
    }
}

function createCircle(x_position, y_position, radius, color) {
    let circle = new Graphics();
    circle.beginFill(color);
    circle.drawCircle(0, 0, radius);
    circle.endFill();
    circle.x = x_position;
    circle.y = y_position;
    
    return circle;
}

function increaseCircleSize(circle) {
    let sizeIncrement = 3;
    circle.width += sizeIncrement;
    circle.height += sizeIncrement;
}

setup();

// Add the canvas generated by PIXI to the DOM.
document.body.appendChild(app.view);